name: Build Leno APK
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      - name: Fix SDK and create gradlew with CORRECT Gradle version
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          gradle wrapper --gradle-version 8.13
          chmod +x gradlew
          ./gradlew --version

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Leno-debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
